# .github/workflows/auto-close-prs.yml
name: Auto-Close Incoming PRs

on:
  pull_request_target:
    types: [opened]

jobs:
  auto-close:
    runs-on: ubuntu-latest
    steps:
      - name: Comment and close PR
        env:
          GH_TOKEN: ${{ secrets.BOT_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO: ${{ github.repository }}
        run: |
          COMMENT="So that we can focus on supporting our connector contributors, we do not accept PRs in this repo. Please feel free to post an issue in https://github.com/airbytehq/airbyte. We encourage contributions in all of our other public repos including https://github.com/airbytehq/airbyte.";

          OWNER=$(echo "$REPO" | cut -d'/' -f1)
          REPO_NAME=$(echo "$REPO" | cut -d'/' -f2)

          echo "Posting comment to PR #$PR_NUMBER..."
          curl -s -X POST \
            -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/$OWNER/$REPO_NAME/issues/$PR_NUMBER/comments \
            -d "$(jq -nc --arg body "$COMMENT" '{body: $body}')"

          echo "Closing PR #$PR_NUMBER..."
          curl -s -X PATCH \
            -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/$OWNER/$REPO_NAME/pulls/$PR_NUMBER \
            -d '{"state": "closed"}'


